ROSEN-A/ROSEN-Group-A

Documentation/Research/OpenCV.md

Completed documentation for OpenCV

10 research on tech documentation on opencv

---

Documentation/Research/VGG16.md

completed documentation for VGG16

12 research on tech documentation on vgg16

---

Documentation/Meeting/meeting minutes.md

this is to create a meeting minute file that I can put the detail of the client meeting in.

Create Meeting Minute File

---

Documentation/Research/Research on Development Framework.md

Added intro, examples, advantages, why and prerequisites of Angular and D3

Added research of Angular and D3

---

README.md

The readme is updated but not complete

Update readme in main

---

Documentation/Research/README.md

Please review the readme document to see if there is any issues

Updated readme in Research

---

OpenCV/README.md

Added details about files used for the program

Created README.md for object detection program

---

Documentation/Requirement Activities/Project Overview.md

Project overview, deliverables and timeline added.

Created Project Overview.md

---

Documentation/Requirement Activities/Non-functional Requirements.md

refined and added more non-func requirements

63 refine requirements after meeting 3

---

Documentation/Requirement Activities/Data Flow Diagrams (DFDs)/readme.md

60 refine documentation after meeting 3

---

Documentation/Research/Research on Development Framework.md

59 refine documentation after meeting 3

---

Documentation/Meeting Minutes/meeting 3.md

Updated meeting minutes. It specifies what we have discussed in the meeting and that the client was not very happy with our presentation.

58 add meeting minutes 3

---

Documentation/Requirement Activities/Functional Requirements.md
Documentation/Research/Research on Development Framework.md

Function Requirements.md is uploaded based on client's clarifications from meeting 3.

64 refine requirements after meeting 3

---

Documentation/Requirement Activities/Tech Stack.md
Documentation/Requirement Activities/environmental contraints.md

62 refine documentation after meeting 3

---

MySql-Docker/README.md
MySql-Docker/requirements.txt

Details about using Docker for setting up MySQL server and database for the python project

README.md added

---

Website/static/javascript/image.js
Website/static/styles/global-style.css
Website/templates/image.html

This is used to add functionality for labeling image

127 adding functionality contd login

---

Last week/modal.js

151 issue 151 upgrade code

---

Website/templates/index.html

221 issue 2

---

Website/templates/choppedImages.html

This is a placeholder for showing the frames after chopping up the  video

248 issue 1

---

Website/static/styles/index-style.css
Website/static/styles/loading-style.css
Website/templates/loading.html
Website/templates/search.html
Website/templates/uploadImage.html
Website/templates/uploadVideo.html

made some small changes to the progress bar

283 update progress bar

---

Website/server.py
Website/static/styles/result-style.css
Website/templates/result.html
Website/templates/uploadImage.html

- enabled return to uploadImage.html on result.html

Logout button added to result.html

---

Website/templates/testing.html

Added testing.html

---

Website/server.py
Website/static/styles/global-style.css
Website/templates/login.html

An alert will pop up if username/password is wrong

327 issue 1
